#!/bin/sh -f

bin_dir="$HOME/bin/"

if [ ! -d $bin_dir ] 
then
    echo "Directory ${bin_dir} does not exist... Creating..."
    mkdir bin_dir
fi

echo "Copying files to relevant places..."
cp dotfiles/vimrc ~/.vimrc
ln -s $PWD/bin/give_me_a_readme $HOME/bin/give_me_a_readme
